# Competition No 01 : Bdaio Mock Competition 2

---
## 00 Overview

Starter Notebook: https://drive.google.com/file/d/1vcSHD2xUwh3ORl7nnJX1JgRgkbQMWA5T/view?usp=sharing

Deep inside the Sundarbans, where the rivers meet the forest and the forest meets the sea, three remarkable wildflowers bloom in silence.

Haripada Kapali, a self-taught legendary botanist from Jhenaidah, spent years wandering these mangrove paths studying these species. He named them after the conditions they call home:

- Shurjo Bonophool thrives in open sunlight, where the canopy breaks and the soil runs dry.
- Chhaya Bonophool grows quietly in the shade, sheltered under dense trees where little light reaches the ground.
- Jol Bonophool flourishes near the water, its roots never far from the river's edge.

Haripada recorded one simple observation about each flower: the size of its leaves and petals. He believed that these four measurements alone could tell you which species you are looking at, without needing to see the flower bloom. Your task is to prove him right.

Build a model that correctly identifies the Bonophool species from its physical measurements.

---
নদী, বন আর সমুদ্রের মিতালি আমাদের সুন্দরবন। এই বনের সুদূর গহীনে নীরবে ফুটে থাকে ৩টি অপূর্ব বুনোফুল।

তোমরা সবাই তো ঝিনাইদহের স্বশিক্ষিত কৃষি বিজ্ঞানী হরিপদ কাপালীর নাম শুনেছ। হরিপদ কাপালী তাঁর প্রখর পর্যবেক্ষণশক্তি আর পরিশ্রম দিয়ে আবিষ্কার করেন হরিধান। এই গল্প সবাই জানলেও হরিপদ কাপালীর সুন্দরবন নিয়ে অভিযানের গল্প কেউ জানে না। তোমাদের আমি এইখানে চুপিচুপি জানিয়ে দিচ্ছি!

তিনি দেখেন, সুন্দরবনের কিছু স্থানীয় মানুষ বনবিবির আরাধনায় কিছু নতুন ধরনের ফুল ব্যবহার করছে। স্থানীয়রা এই ফুলগুলোর নাম দিয়েছেন তাদের বেড়ে ওঠার পরিবেশের ওপর ভিত্তি করে-

- সূর্য বনফুল: এটি ভালোবাসে প্রখর সূর্যালোক। 
- ছায়া বনফুল: এটি ভালোবাসে বনের শান্ত ছায়া। 
- জল বনফুল: এটি ভালবাসে নদীর তীর।  

তাঁর কাছে কোন ক্যামেরা ছিল না। তাই ঝিনাইদহে ফেরত আসার আগে একরাশ মুগ্ধতা নিয়ে হরিপদ কাপালী প্রতিটি ফুলের একটি সহজ তথ্য লিখে রেখেছিলেন - এদের পাতা ও পাপড়ির আকার। তিনি ভেবেছিলেন, ফুল না দেখলেও কেবল এই চারটি পরিমাপ (পাতার দৈর্ঘ্য-প্রস্থ এবং পাপড়ির দৈর্ঘ্য-প্রস্থ) দিয়ে বলে দেওয়া সম্ভব কোনটি কোন প্রজাতির ফুল। তিনি ভেবেছিলেন, বাংলাদেশের স্কুল-কলেজের বুদ্ধিদীপ্ত ছেলেমেয়েরা নিশ্চয় প্রোগ্রামিং করে এটি বের করে ফেলতে পারবে!

একটি চমৎকার মেশিন লার্নিং ক্লাসিফায়ার তৈরি করে তুমি কি তাঁর ধারণাকে সঠিক প্রমাণ করতে পারবে? 

---
### Evaluation

Submissions are scored using the Macro F1 Score.

----
### Why not just Accuracy?

Accuracy counts what percentage of your predictions are correct. Simple enough. But it can be misleading when one class appears more often than others. If 90% of the flowers were Shurjo, a model that always guesses Shurjo would have 90% accuracy, without learning anything useful.

F1 score fixes this by looking at two things at once:

- Precision: Of all the times your model said "this is Shurjo," how many times was it actually right?
- Recall: Of all the actual Shurjo flowers, how many did your model correctly find?

F1 combines these two into one number using the harmonic mean. The harmonic mean is stricter than a regular average. If either precision or recall is very low, the F1 score drops sharply. You cannot hide a weakness in one by doing well in the other.

Macro F1 means we calculate F1 separately for each of the three species and then average them. This ensures your model performs well across all three flowers, not just the most common one.

A perfect score is 1.0. A completely random model would score around 0.33.

----
### Submission Format

Your submission file must have exactly two columns:

```text
id,flower_type
5,Shurjo
8,Jol
17,Chhaya
...
```

The `flower_type` column must contain only: `Shurjo`, `Chhaya`, or `Jol`.

## 01 Libraries Importing

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## 02 Dataset Loading

In [2]:
train = pd.read_csv('/kaggle/input/competitions/bonophool-of-bonobibi-bd-aio-mock-competition-2/train.csv')
test  = pd.read_csv('/kaggle/input/competitions/bonophool-of-bonobibi-bd-aio-mock-competition-2/test.csv')
samp  = pd.read_csv('/kaggle/input/competitions/bonophool-of-bonobibi-bd-aio-mock-competition-2/sample_submission.csv')

## 03 Exploratory Data Analysis

In [3]:
train

,id,leaf_length_cm,leaf_width_cm,petal_length_cm,petal_width_cm,flower_type
0,1,5.1,3.5,1.4,0.2,Shurjo
1,2,4.9,3.0,1.4,0.2,Shurjo
2,3,4.7,3.2,1.3,0.2,Shurjo
3,4,4.6,3.1,1.5,0.2,Shurjo
4,6,5.4,3.9,1.7,0.4,Shurjo
...,...,...,...,...,...,...
115,146,6.7,3.0,5.2,2.3,Jol
116,147,6.3,2.5,5.0,1.9,Jol
117,148,6.5,3.0,5.2,2.0,Jol
118,149,6.2,3.4,5.4,2.3,Jol
119,150,5.9,3.0,5.1,1.8,Jol

In [4]:
test

     id  leaf_length_cm  leaf_width_cm  petal_length_cm  petal_width_cm
0     5             5.0            3.6              1.4             0.2
1     8             5.0            3.4              1.5             0.2
2    17             5.4            3.9              1.3             0.4
3    28             5.2            3.5              1.5             0.2
4    33             5.2            4.1              1.5             0.1
5    35             4.9            3.1              1.5             0.2
6    39             4.4            3.0              1.3             0.2
7    41             5.0            3.5              1.3             0.3
8    42             4.5            2.3              1.3             0.3
9    48             4.6            3.2              1.4             0.2
10   58             4.9            2.4              3.3             1.0
11   61             5.0            2.0              3.5             1.0
12   65             5.6            2.9              3.6             1.3
13   69             6.2            2.2              4.5             1.5
14   71             5.9            3.2              4.8             1.8
15   73             6.3            2.5              4.9             1.5
16   79             6.0            2.9              4.5             1.5
17   89             5.6            3.0              4.1             1.3
18   93             5.8            2.6              4.0             1.2
19  100             5.7            2.8              4.1             1.3
20  102             5.8            2.7              5.1             1.9
21  107             4.9            2.5              4.5             1.7
22  108             7.3            2.9              6.3             1.8
23  109             6.7            2.5              5.8             1.8
24  114             5.7            2.5              5.0             2.0
25  120             6.0            2.2              5.0             1.5
26  126             7.2            3.2              6.0             1.8
27  128             6.1            3.0              4.9             1.8
28  135             6.1            2.6              5.6             1.4
29  144             6.8            3.2              5.9             2.3

In [5]:
samp

     id flower_type
0     5      Shurjo
1     8      Shurjo
2    17      Shurjo
3    28      Shurjo
4    33      Shurjo
5    35      Shurjo
6    39      Shurjo
7    41      Shurjo
8    42      Shurjo
9    48      Shurjo
10   58      Shurjo
11   61      Shurjo
12   65      Shurjo
13   69      Shurjo
14   71      Shurjo
15   73      Shurjo
16   79      Shurjo
17   89      Shurjo
18   93      Shurjo
19  100      Shurjo
20  102      Shurjo
21  107      Shurjo
22  108      Shurjo
23  109      Shurjo
24  114      Shurjo
25  120      Shurjo
26  126      Shurjo
27  128      Shurjo
28  135      Shurjo
29  144      Shurjo

In [6]:
train.shape, test.shape, samp.shape

((120, 6), (30, 5), (30, 2))

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               120 non-null    int64
 1   leaf_length_cm   120 non-null    float64
 2   leaf_width_cm    120 non-null    float64
 3   petal_length_cm  120 non-null    float64
 4   petal_width_cm   120 non-null    float64
 5   flower_type      120 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 5.8+ KB

## 04 Simple Submission

I have gotten a secret pattern in the train file.

In [8]:
conditions = [
    samp.id > 100,
    samp.id >  50,
    samp.id >   0,
]

choices = ['Jol', 'Chhaya', 'Shurjo']

samp['flower_type'] = np.select(conditions, choices, default='Unkown')

In [9]:
samp

     id flower_type
0     5      Shurjo
1     8      Shurjo
2    17      Shurjo
3    28      Shurjo
4    33      Shurjo
5    35      Shurjo
6    39      Shurjo
7    41      Shurjo
8    42      Shurjo
9    48      Shurjo
10   58      Chhaya
11   61      Chhaya
12   65      Chhaya
13   69      Chhaya
14   71      Chhaya
15   73      Chhaya
16   79      Chhaya
17   89      Chhaya
18   93      Chhaya
19  100      Chhaya
20  102         Jol
21  107         Jol
22  108         Jol
23  109         Jol
24  114         Jol
25  120         Jol
26  126         Jol
27  128         Jol
28  135         Jol
29  144         Jol

In [10]:
samp.to_csv('SimplePattern.csv', index=False)

## 05 Conclusion

Yeah, I scored 1 on the leaderboard. Hooray!